<?php

namespace Fp\Core;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-31 at 16:34:21.
 */
class DateTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Date
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
          $this->object = new Date;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Fp\Core\Date::fromFormat
     * @todo   Implement testFromFormat().
     */
    public function testFromFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::fromMysqlDate
     * @todo   Implement testFromMysqlDate().
     */
    public function testFromMysqlDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::fromStrtotime
     * @todo   Implement testFromStrtotime().
     */
    public function testFromStrtotime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::fromMysqlDateTime
     * @todo   Implement testFromMysqlDateTime().
     */
    public function testFromMysqlDateTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::fromUnixTime
     * @todo   Implement testFromUnixTime().
     */
    public function testFromUnixTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::day_short
     * @todo   Implement testDay_short().
     */
    public function testDay_short() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::day_fr_short
     * @todo   Implement testDay_fr_short().
     */
    public function testDay_fr_short() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::day
     * @todo   Implement testDay().
     */
    public function testDay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::day_fr
     * @todo   Implement testDay_fr().
     */
    public function testDay_fr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::dayNumInWeek
     * @todo   Implement testDayNumInWeek().
     */
    public function testDayNumInWeek() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::dayWeekNum
     * @todo   Implement testDayWeekNum().
     */
    public function testDayWeekNum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::month
     * @todo   Implement testMonth().
     */
    public function testMonth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::month_fr
     * @todo   Implement testMonth_fr().
     */
    public function testMonth_fr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::month_short
     * @todo   Implement testMonth_short().
     */
    public function testMonth_short() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::year
     * @todo   Implement testYear().
     */
    public function testYear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::second
     * @todo   Implement testSecond().
     */
    public function testSecond() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::min
     * @todo   Implement testMin().
     */
    public function testMin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::hour
     * @todo   Implement testHour().
     */
    public function testHour() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::month_num
     * @todo   Implement testMonth_num().
     */
    public function testMonth_num() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::day_num
     * @todo   Implement testDay_num().
     */
    public function testDay_num() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::minuteNumInDay
     * @todo   Implement testMinuteNumInDay().
     */
    public function testMinuteNumInDay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::unixTime
     * @todo   Implement testUnixTime().
     */
    public function testUnixTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::format
     * @todo   Implement testFormat().
     */
    public function testFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::iso8601
     * @todo   Implement testIso8601().
     */
    public function testIso8601() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::rfc2822
     * @todo   Implement testRfc2822().
     */
    public function testRfc2822() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::rfc3339
     * @todo   Implement testRfc3339().
     */
    public function testRfc3339() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::mysqlDateTime
     * @todo   Implement testMysqlDateTime().
     */
    public function testMysqlDateTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::mysqlDate
     * @todo   Implement testMysqlDate().
     */
    public function testMysqlDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::getAge
     * @todo   Implement testGetAge().
     */
    public function testGetAge() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::isToday
     * @todo   Implement testIsToday().
     */
    public function testIsToday() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::isTomorrow
     * @todo   Implement testIsTomorrow().
     */
    public function testIsTomorrow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::remainingTime
     * @todo   Implement testRemainingTime().
     */
    public function testRemainingTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::remainingDays
     * @todo   Implement testRemainingDays().
     */
    public function testRemainingDays() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Date::humanize
     * @todo   Implement testHumanize().
     */
    public function testHumanize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
