<?php

namespace Fp\Core;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-31 at 16:35:10.
 */
class FilterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Filter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new Filter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Fp\Core\Filter::custom
     * @todo   Implement testCustom().
     */
    public function testCustom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::addSlashes
     * @todo   Implement testAddSlashes().
     */
    public function testAddSlashes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::fixUtf8
     * @todo   Implement testFixUtf8().
     */
    public function testFixUtf8() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::utf8
     * @todo   Implement testUtf8().
     */
    public function testUtf8() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::iso8859_1
     * @todo   Implement testIso8859_1().
     */
    public function testIso8859_1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::int
     */
    public function testInt() {
        $this->assertEquals(null, \Fp\Core\Filter::int(null));
        $this->assertEquals(0,    \Fp\Core\Filter::int(0));
        $this->assertEquals(1425,   \Fp\Core\Filter::int(14.25));
        $this->assertEquals(16,   \Fp\Core\Filter::int(16));        
        $this->assertEquals(null, \Fp\Core\Filter::int('test string'));
        $this->assertEquals(null, \Fp\Core\Filter::int(['test key']));
        $this->assertEquals(99, \Fp\Core\Filter::int(['test'], ['test' => 99]));
        $this->assertEquals(99, \Fp\Core\Filter::int(['test','test1'], ['test' => ['test1' => 99]]));
        $this->assertEquals(null, \Fp\Core\Filter::int(['test','test1'], ['test' => ['test1' => 'string']]));
    }

    /**
     * @covers Fp\Core\Filter::float
     * @todo   Implement testFloat().
     */
    public function testFloat() {
        $this->assertEquals(null, \Fp\Core\Filter::float(null));
        $this->assertEquals(0,    \Fp\Core\Filter::float(0));
        $this->assertEquals(3.14,    \Fp\Core\Filter::float(3.14));
    }

    /**
     * @covers Fp\Core\Filter::intList
     * @todo   Implement testIntList().
     */
    public function testIntList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::alnum
     * @todo   Implement testAlnum().
     */
    public function testAlnum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::classname
     * @todo   Implement testClassname().
     */
    public function testClassname() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::variablename
     * @todo   Implement testVariablename().
     */
    public function testVariablename() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::id
     * @todo   Implement testId().
     */
    public function testId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::b64Decode
     * @todo   Implement testB64Decode().
     */
    public function testB64Decode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::b64Encode
     * @todo   Implement testB64Encode().
     */
    public function testB64Encode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::b64WebDecode
     * @todo   Implement testB64WebDecode().
     */
    public function testB64WebDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::b64WebEncode
     * @todo   Implement testB64WebEncode().
     */
    public function testB64WebEncode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::b64Compress
     * @todo   Implement testB64Compress().
     */
    public function testB64Compress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::b64Decompress
     * @todo   Implement testB64Decompress().
     */
    public function testB64Decompress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::urlDecode
     * @todo   Implement testUrlDecode().
     */
    public function testUrlDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::urlEncode
     * @todo   Implement testUrlEncode().
     */
    public function testUrlEncode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::url
     * @todo   Implement testUrl().
     */
    public function testUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::email
     * @todo   Implement testEmail().
     */
    public function testEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::mysqlDate
     * @todo   Implement testMysqlDate().
     */
    public function testMysqlDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::mysqlDateTime
     * @todo   Implement testMysqlDateTime().
     */
    public function testMysqlDateTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::text
     * @todo   Implement testText().
     */
    public function testText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::decodeHtmlChars
     * @todo   Implement testDecodeHtmlChars().
     */
    public function testDecodeHtmlChars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::encodeHtmlChars
     * @todo   Implement testEncodeHtmlChars().
     */
    public function testEncodeHtmlChars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::htmlDoubleQuote
     * @todo   Implement testHtmlDoubleQuote().
     */
    public function testHtmlDoubleQuote() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::htmlAttr
     * @todo   Implement testHtmlAttr().
     */
    public function testHtmlAttr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::html
     * @todo   Implement testHtml().
     */
    public function testHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::htmlToText
     * @todo   Implement testHtmlToText().
     */
    public function testHtmlToText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::repetition
     * @todo   Implement testRepetition().
     */
    public function testRepetition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::spam
     * @todo   Implement testSpam().
     */
    public function testSpam() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::DbSafe
     * @todo   Implement testDbSafe().
     */
    public function testDbSafe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::raw
     * @todo   Implement testRaw().
     */
    public function testRaw() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::accent
     * @todo   Implement testAccent().
     */
    public function testAccent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::htmlspecialchars
     * @todo   Implement testHtmlspecialchars().
     */
    public function testHtmlspecialchars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::fileName
     * @todo   Implement testFileName().
     */
    public function testFileName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::dirName
     * @todo   Implement testDirName().
     */
    public function testDirName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::array_
     * @todo   Implement testArray_().
     */
    public function testArray_() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fp\Core\Filter::arrayOfInt
     * @todo   Implement testArrayOfInt().
     */
    public function testArrayOfInt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
